[theme]
name = "slick"
[theme.overrides]
info_bg = "#4560CE"
info_fg = "#FFFFFF"
idle_bg = "#1C1C1C"
idle_fg = "#FFFFFF"
good_bg = "#859900"
good_fg = "#232c31"
warning_bg = "#FFB100"
warning_fg = "#232c31"
critical_bg = "#FF0000"
critical_fg = "#FFFFFF"
separator = ""
separator_bg = "#002933"
separator_fg = "#A7BBC0"

[icons]
name = "awesome"
[icons.overrides]

[[block]]
block = "custom"
command = "sh .scripts/ssh-rust.sh"
interval = 5

[[block]]
block = "uptime"

[[block]]
block = "weather"
format = "{weather} {temp}°, {wind} m/s"
service = { name = "openweathermap", api_key = "e9dfc84bc65c9e141608847a204ee894", city_id = "3057963", units = "metric" }

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = "/:"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 2
format = "{max}°C"

[[block]]
block = "net"
device = "enp2s0"
ssid = false
ip = false
speed_up = false
speed_down = true
graph_up = false
graph_down = false
interval = 5

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 5
format = " %a %-d %b %H:%M"
