[theme]
name = "slick"
[theme.overrides]
info_bg = "#268BD2"
info_fg = "#232c31"
idle_bg = "#1C1C1C"
idle_fg = "#E3E9FF"
good_bg = "#859900"
good_fg = "#232c31"
warning_bg = "#b58900"
warning_fg = "#232c31"
critical_bg = "#FF8888"
critical_fg = "#232c31"
separator = ""
separator_bg = "#002933"
separator_fg = "#A7BBC0"

[icons]
name = "awesome"
[icons.overrides]

[[block]]
block = "uptime"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = "/:"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 2
format = "{max}° max"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 5
format = " %a %-d %b %H:%M"
