#!/usr/bin/env bash

artist=$(/usr/bin/cmus-remote -Q 2>/dev/null | grep "tag artist" | cut -d " " -f 3- | head -1)
title=$(/usr/bin/cmus-remote -Q 2>/dev/null | grep title | cut -d " " -f 3- | head -1)
duration=$(/usr/bin/cmus-remote -Q 2>/dev/null | grep duration | cut -d " " -f 2 | head -1)
position=$(/usr/bin/cmus-remote -Q 2>/dev/null | grep position | cut -d " " -f 2 | head -1)

convertsecs() {
 ((m=(${1}%3600)/60))
 ((s=${1}%60))
 printf "%02d:%02d\n" $m $s
}

if [ -n "$artist" ]; then
  echo "  $artist - $title  [$(convertsecs $position)/$(convertsecs $duration)]  "
fi
