#!/bin/sh
#
# wm independent hotkeys
#

# terminal emulator
super + Return
	urxvt

super + shift + Return
	termite

super + z
	dmenu_run -i -p 'Arch Linux ' -fn 'Iosevka:pixelsize=17' -nb '#1E1816' -nf '#F2DEA3' -sf '#1E1816' -sb '#F2DEA3'

alt + space
	j4-dmenu-desktop --dmenu="dmenu -fn "Iosevka:bold:pixelsize=17" -nb '#1E1816' -nf '#F2DEA3' -sb '#F2DEA3' -sf '#1E1816' -i"

super + space
	rofi -show drun -show-icons -drun-icon-theme Newaita-dark

super + m
	find ~/ -not -path '*/\.*' 2> /dev/null | sed 's/ /\\ /g' | sort -f | rofi -dmenu | xargs xdg-open

super + F1
	nautilus --new-window

super + F2
	firefox

super + shift + F2
	firefox --private-window

super + F3
	thunderbird

super + v ; {w,o,e,s,n,m,p,g,v,t,f,r,z}
	{firefox,lowriter,subl,smplayer,urxvt -e ncmpcpp,mousepad,pavucontrol,gimp,vlc,thunar,nautilus --new-window,urxvt -e ranger,zathura}

super + shift + x
	rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'

super + ctrl + r
	cp ~/.config/bspwm/Bspwm-Dark-Cosmos/polybar/config /home/lubomir/.config/polybar/

Print
	scrot

super + Print
	scrot -d 8

super + l
	~/.config/lock.sh

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

super + alt + r
	~/.config/bspwm/bspwmrc

#######################
###  bspwm hotkeys  ###
#######################

# quit bspwm normally
super + alt + Escape
	bspc quit

# Power menu
super + 0
	sh ~/.scripts/power-menu-bspwm.sh

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + f
#	bspc desktop -l next
	sh ~/.config/bspwm/Bspwm-Dark-Orange/monocle_layout.sh

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# Flip layout vertically/horizontally
super + {_,shift + }d
	bspc node @/ --flip {vertical,horizontal}

# swap the current node and the biggest node
super + g
	bspc node -s biggest.local

# Rotate desktop
super + {_,shift + }r
	bspc node @/ --rotate {90,-90}

# Circulate the leaves of the tree
super + shift + c
	bspc node @/ --circulate {backward,forward}

#
# state/flags
#

# set the window state
#super + {t,shift + t,shift + f}
#	bspc node -t {tiled,pseudo_tiled,fullscreen}

# alternate between pseudo tiled & tiled layout
super + shift + s
     if [ -z "$(bspc query -N -n focused.pseudo_tiled)" ]; then \
         bspc node focused -t pseudo_tiled; \
     else \
         bspc node focused -t tiled; \
     fi

# alternate between fullscreen & tiled layout
super + shift + f
    if [ -z "$(bspc query -N -n focused.fullscreen)" ]; then \
        bspc node focused -t fullscreen; \
    else \
        bspc node focused -t tiled; \
    fi

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# Toogle tiling of window
super + s
	bspc query --nodes -n focused.tiled && state=floating || state=tiled; \
	bspc node --state \~$state

#
# focus/swap
#

## focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
 	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
#super + ctrl + {h,j,k,l}
#	bspc node -p {west,south,north,east}
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

super + w
	bspc node -f @/

# Make node split ratios equal or balanced.  The former applies to the
# root of the tree to equalise all split ratios.  The latter applies to
# the parent node to even out manually-split windows.
super + e ; {super + e,e}
	bspc node {@/ --equalize,@parent --balance}

# Global Dynamic gaps
alt + bracket{left,right}
	bspc config window_gap "$(($(bspc config window_gap) {-,+} 2 ))"
# Original gaps
alt + backslash
	bspc config window_gap 0
alt + 0
	bspc config window_gap 0

# Focused Dynamic gaps
super + shift + bracket{left,right}
	bspc config -d focused window_gap "$(($(bspc config -d focused window_gap) {-,+} 2 ))"
# Original gaps
super + shift + backslash
	bspc config -d focused window_gap 0

super + shift + KP_0
	bspc config -d focused window_gap 0

# Global Dynamic borders
alt + ctrl + bracket{left,right}
	bspc config border_width "$(($(bspc config border_width) {-,+} 1 ))"
# Original borders
alt + ctrl + backslash
	bspc config border_width 3

# Focused Dynamic borders
super + ctrl + bracket{left,right}
	bspc config -d focused border_width "$(($(bspc config -d focused border_width) {-,+} 1 ))"
# Original borders
super + ctrl + backslash
	bspc config -d focused border_width 3
####################################

# Expand tiled space
super + alt + {Left,Down,Up,Right}
	bspc node {@west -r -20,@south -r +20,@north -r -20,@east -r +20}

# Contract tiled space
super + alt + ctrl + {Left,Down,Up,Right}
	bspc node {@east -r -20,@north -r +20,@south -r -20,@west -r +20}

# move a floating window
alt + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# empty frame over half desktop
super + shift + {h,j,k,l}
	sh ~/.config/bspwm/external/bspwm_smart_move {west,south,north,east}

#
# RECEPTACLES
#

super + x ; c
	bspc node -i

super + x ; v
	sh ~/.config/bspwm/external/bspwm_smart_presel

super + x ; x
	bspc node 'any.leaf.!window.local' -k

#
# Pulse Audio controls
#

## Volume control
# XF86Audio{RaiseVolume,LowerVolume,Mute}
# 	amixer {-q set Master 5%+,-q set Master 5%-,set Master toggle} & canberra-gtk-play -i audio-volume-change -d "changeVolume"

XF86AudioRaiseVolume
	sh ~/.scripts/volume-notification/volume.sh up & canberra-gtk-play -i audio-volume-change -d "changeVolume"

XF86AudioLowerVolume
	sh ~/.scripts/volume-notification/volume.sh down & canberra-gtk-play -i audio-volume-change -d "changeVolume"

XF86AudioMute
	sh ~/.scripts/volume-notification/volume.sh mute & canberra-gtk-play -i audio-volume-change -d "changeVolume"

#
# wallpapers
#

super + shift + w
	feh --randomize --bg-fill ~/Pictures/backgrounds/bspwm-dark-cosmos/*

#
# notify restart
#

super + backslash
	killall dunst; notify-send 'restart dunst'
