#!/usr/bin/env bash

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color "$orangeColor"
hc set frame_border_normal_color "$bg1Color"
hc set frame_bg_normal_color "$bg1Color"
hc set frame_bg_active_color "$orangeColor"
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 10

hc attr theme.active.color "$orangeColor"
hc attr theme.normal.color "$bg1Color"
hc attr theme.urgent.color "$redColor"
hc attr theme.inner_width 0
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color "$bg1Color"
hc attr theme.active.inner_color "$darkOrangeColor"
hc attr theme.active.outer_color "$darkOrangeColor"
hc attr theme.background_color "$bg1Color"

# window settings
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set default_frame_layout 3

# monitor settings
hc set swap_monitors_to_get_tag 0

# other
herbstclient set tree_style '╾│ ├└╼─┐'
herbstclient set focus_follows_mouse 1
herbstclient set focus_crosses_monitor_boundaries 0

