#! /bin/sh

pkill sxhkd &
sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d          

bspc config border_width         2
bspc config window_gap           10

bspc config focused_sticky_border_color     "#FFB600"
bspc config focused_border_color            "#2AA198"
#bspc config focused_border_color            "#2AA198"
bspc config normal_border_color             "#1D414A"
bspc config urgent_border_color             "#red"
bspc config active_border_color             "#magenta"
bspc config presel_feedback_color           "#2AA198"
bspc config window_gap                      "#bspwm_window_gap"


bspc config top_padding			26
bspc config right_padding		0
bspc config bottom_padding		0
bspc config left_padding		0

# bspc config automatic_scheme spiral
# bspc config initial_polarity first_child

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# RULES

bspc rule -a '*:zathura' state=tiled
bspc rule -a Gimp desktop='^4' follow=on
bspc rule -a Gimp-2.10 desktop='^4' follow=on
bspc rule -a Transmission-gtk desktop='^9' follow=on
bspc rule -a '*:libreofficedev' desktop='^5' state=tiled follow=on
bspc rule -a '*:soffice' desktop='^5' state=tiled follow=on
#bspc rule -a Soffice state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on
bspc rule -a Galculator state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a SuperTuxKart state=tiled


bspc config external_rules_command sh ~/.scripts/bspwm/windows_rules.sh

### AUTOSTART ###

pkill compton
compton -b --config ~/.config/compton.conf &
###############
$HOME/.config/polybar/launch.sh
#feh --bg-fill /home/lubomir/Pictures/backgrounds/mosty.jpg &
#feh --bg-tile /home/lubomir/Pictures/backgrounds/bspwm-solarized-green2.png &
feh --bg-fill /home/lubomir/Pictures/backgrounds/by_upload.jpg &
#feh --bg-fill /home/lubomir/Pictures/backgrounds/sky-solarized.jpg &
#nitrogen --restore &
###############
#pkill start-pulseaudio-x11
start-pulseaudio-x11 &
###############
pkill gnome-settings-daemon
gnome-settings-daemon &
setxkbmap -layout "us,sk(qwerty),cz(qwerty)" -option grp:alt_shift_toggle &
#pulseaudio --kill &
#pulseaudio --start &
pkill polkit-gnome-authentication-agent-1
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xrdb -load ~/.Xresources &
numlockx on &
xset -dpms s off &
# Redshift
pkill redshift
sleep 5; redshift -l 48.16:17.11 &
