#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

feh --bg-fill /home/lubomir/Pictures/backgrounds/herbstluftwm-canvas/dark_sky.jpg &

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-w spawn feh --bg-fill --randomize /home/lubomir/Pictures/backgrounds/herbstluftwm-canvas/*

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn ${TERMINAL:-urxvt} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-F1 spawn nautilus --new-window
hc keybind $Mod-F2 spawn firefox
hc keybind $Mod-Shift-F2 spawn firefox -private-window
hc keybind $Mod-F3 spawn thunderbird
hc keybind $Mod-g spawn subl
hc keybind $Mod-d spawn rofi -show drun -show-icons -drun-icon-theme Newaita-dark
hc keybind $Mod-n spawn urxvt -e ncmpcpp
hc keybind $Mod-m spawn smplayer
hc keybind $Mod-o spawn lowriter
hc keybind $Mod-h spawn viewnior
hc keybind $Mod-l spawn sh /home/lubomir/.config/lock.sh
hc keybind Print spawn scrot
hc keybind Shift-Print spawn scrot -d 8
hc keybind Alt-space spawn j4-dmenu-desktop --dmenu="dmenu -fn "Iosevka:bold:pixelsize=17.5" -nb '#1C1C1C' -nf '#FFFFFF' -sb '#3D60E5' -sf '#FFFFFF' -i"
hc keybind Alt-r spawn cp ~/.config/herbstluftwm/Canvas-theme/polybar/config ~/.config/polybar/

# power menu
hc keybind $Mod-0 spawn sh ~/.scripts/power-menu-hlwm.sh

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
# hc keybind $Mod-h     focus left
# hc keybind $Mod-j     focus down
# hc keybind $Mod-k     focus up
# hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
# hc keybind $Mod-Shift-h     shift left
# hc keybind $Mod-Shift-j     shift down
# hc keybind $Mod-Shift-k     shift up
# hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-v       split   bottom  0.5
hc keybind $Mod-b       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-a split explode

# resizing frames
resizestep=0.05
# hc keybind $Mod-Control-h       resize left +$resizestep
# hc keybind $Mod-Control-j       resize down +$resizestep
# hc keybind $Mod-Control-k       resize up +$resizestep
# hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# gaps size
hc keybind $Mod-Control-0   spawn sh ~/.scripts/herbstluftwm/gap-zero.sh
hc keybind $Mod-Control-backslash   spawn sh ~/.scripts/herbstluftwm/gap-default.sh

hc keybind $Mod-Control-equal   spawn sh ~/.scripts/herbstluftwm/increase.sh
hc keybind $Mod-Control-minus   spawn sh ~/.scripts/herbstluftwm/decrease.sh

## hotkeys
# hc keybind XF86AudioLowerVolume spawn ~/.config/herbstluftwm/volume.sh down
# hc keybind XF86AudioRaiseVolume spawn ~/.config/herbstluftwm/volume.sh up
# hc keybind XF86AudioMute spawn ~/.config/herbstluftwm/volume.sh mute
#
# hc keybind XF86AudioLowerVolume spawn amixer -q set Master 5%- unmute down
# hc keybind XF86AudioRaiseVolume spawn amixer -q set Master 5%+ unmute up
# hc keybind XF86AudioMute spawn amixer -q set Master toggle mute

hc keybind XF86AudioRaiseVolume spawn sh ~/.scripts/volume-notification/volume-light.sh up
hc keybind XF86AudioLowerVolume spawn sh ~/.scripts/volume-notification/volume-light.sh down
hc keybind XF86AudioMute spawn sh ~/.scripts/volume-notification/volume-light.sh mute



# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

## set initial frame padding
herbstclient pad 0 25 0 0
# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-x remove
hc keybind $Mod-Shift-s floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-e spawn sh ~/.scripts/float-maximize.sh
hc keybind $Mod-f spawn sh ~/.scripts/maximize.sh
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layorut +1

hc keybind $Mod-s spawn sh ~/.config/herbstluftwm/scripts/toggle_single_float.sh

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#2B2B2B'
hc set frame_border_normal_color '#1B1B1B'
hc set frame_bg_normal_color '#7D7D7D'
hc set frame_bg_active_color '#3D60E5'
hc set frame_active_opacity '60'
hc set frame_normal_opacity '20'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 2
hc set frame_gap 6
hc set focus_follows_mouse 0

hc attr theme.active.color '#5D7DFB'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color '#272727'
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#454545'
hc attr theme.active.outer_color '#454545'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule class=Transmission-gtk tag=9
hc rule class=Gimp-2.10 tag=4
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

## layout
# herbstclient load "(split horizontal:0.750000:0 (clients vertical:0 0x1a0000a) (split vertical:0.300000:0 (clients vertical:0) (clients vertical:0)))"

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
#hc set_monitors 1920x1080+0+0

# # find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" $monitor &
# done

# add an external panel
{
    pids=( )
    # reserve some space for the panel on monitor 0
    hc pad 0 "" "" 0
    # start the panel itself and remember its pid
    polybar example -r &
    pids+=( $! )
    # or start another panel:
    # mypanel &
    # pids+=( $! )
    # wait until the panels should be stopped
    herbstclient -w '(quit_panel|reload)'
    # stopp all started panels
    kill ${pids[@]}
} &

# Autorun Apps
pkill picom && sleep 1; picom -b &
sleep 1; numlockx on &
killall dunst; notify-send "restart dunst" &
pkill greenclip && sleep 1; greenclip daemon &
sleep 1; greenclip clear &
sleep 1; xrdb ~/.Xresources &
xfsettingsd &
#perl ~/.scripts/herbstluftwm/decoration-per-tag.pl &
setxkbmap -layout "us,sk(qwerty),cz(qwerty)" -option grp:alt_shift_toggle &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pkill redshift && sleep 5; redshift -l 48.16:17.11 &
xset -dpms s off &
